### PR TITLE
fix(@cubejs-core): Add type definition for compareDateRange, fix #1621

### LINKED ISSUE #1621: `compareDateRange` needs to be added to the type definitions for
**Describe the bug**

The article on https://cube.dev/blog/comparing-data-over-different-time-periods/ describes a new `compareDateRange` property available on TimeDimensions. Based on what I could see this is available in the repository however it doesn't look like the type definitions were added so it is unavailable for Typescript projects. 

**To Reproduce**
1. npm install the latest cubejs-core (0.24.8 as of this writing)
2. Include cubejs-core
3. Try to instantiate a query with a compareDateRange property in a Typescript file.

**Expected behavior**
Typescript projects can use the `compareDateRange` property

**Version:**
 * `@cubejs-client/core": "^0.24.8"`
 * ` @cubejs-client/react": "^0.24.8"`

### PR DESCRIPTION
**Pull request by cbroome**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

#1621 

**Description of Changes Made (if issue reference is not provided)**

Added compareDateRanges as a type to TimeDimension

### CODE REVIEW

**Review by vasilev-alex — CHANGES_REQUESTED** [review]
Hi @cbroome! Thanks for the PR.

The update you're suggesting does not cover all possible cases for `compareDateRange` https://cube.dev/docs/query-format#time-dimensions-format

On top of that, the `compareDateRange` and `dateRange` props are mutually exclusive, so we should consider it.

**Comment by cbroome** [comment]
@vasilev-alex updated, let me know if that works.

File: packages/cubejs-client-core/index.d.ts [hunk 1]
```diff
@@ -680,11 +680,21 @@ declare module '@cubejs-client/core' {
...
-  };
+  }
+
+  export interface TimeDimensionComparison extends TimeDimensionBase {
+    compareDateRange: Array<string | Array<string>>;
+    dateRange?: never;
+  }
+
+  export interface TimeDimensionRanged extends TimeDimensionBase {
+    dateRange?: string | string[];
```
Comment (vasilev-alex) [inline packages/cubejs-client-core/index.d.ts:694]: I think the second option should be `[string, string]`

File: packages/cubejs-client-core/index.d.ts [hunk 2]
```diff
@@ -680,11 +680,21 @@ declare module '@cubejs-client/core' {
 
   export type TimeDimensionGranularity = 'second' | 'minute' | 'hour' | 'day' | 'week' | 'month' | 'year';
 
-  export type TimeDimension = {
+  export interface TimeDimensionBase {
```
Comment (vasilev-alex) [inline packages/cubejs-client-core/index.d.ts:683]: Could you please change to be `type`s? While interfaces also work here, our docs-gen (which generates the docs' md files) works better with type definitions rather than with interfaces.

**Review by vasilev-alex — CHANGES_REQUESTED** [review]

File: packages/cubejs-client-core/index.d.ts (hunk 1 above)
Comment (cbroome) [reply packages/cubejs-client-core/index.d.ts:694]: Should it? It was `dateRange?: string | string[];` in the original code.

File: packages/cubejs-client-core/index.d.ts (hunk 2 above)
Comment (cbroome) [reply packages/cubejs-client-core/index.d.ts]: Done.

File: packages/cubejs-client-core/index.d.ts (hunk 1 above)
Comment (vasilev-alex) [reply packages/cubejs-client-core/index.d.ts:694]: It was incorrect then. `dateRange` is either a string or an array of two dates.

File: packages/cubejs-client-core/index.d.ts [hunk 3]
```diff
@@ -680,12 +680,22 @@ declare module '@cubejs-client/core' {
...
 
-  export type TimeDimension = {
+  export type TimeDimensionBase = {
     dimension: string;
-    dateRange?: string | string[];
     granularity?: TimeDimensionGranularity;
   };
 
+  export type TimeDimensionComparison = TimeDimensionBase & {
+    compareDateRange: Array<string | Array<string>>;
```
Comment (vasilev-alex) [inline packages/cubejs-client-core/index.d.ts:689]: `Array<string | [string, string]>`

**Comment by cbroome** [comment]
@vasilev-alex Just to follow-up, making the DateRange check more explicit did necessitate some updates in my code. It could be a rude surprise to other users if they were playing loose like I was.
